AVR_System/config/routes.rb
Rails.application.routes.draw do
  resources :items_mods_joins
  resources :mods
  resources :menuitems
  resources :categories
  resources :tables
  resources :tables_items_joins
  get 'sessions/new'
  resources :waiters

  match "/signout" => "sessions#destroy", via: [:get,:post]
  match "/signin" => "sessions#new", via: [:get,:post]
  match "/login" => "sessions#create", via: [:get,:post]

  root to: 'waiters#index'
end

AVR_System/app/models/mod.rb
class Mod < ApplicationRecord
end

AVR_System/app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_action :set_mod, only: [:show, :edit, :update, :destroy]

  # GET /mods
  # GET /mods.json
  def index
    @mods = Mod.all
  end

  # GET /mods/1
  # GET /mods/1.json
  def show
  end

  # GET /mods/new
  def new
    @mod = Mod.new
  end

  # GET /mods/1/edit
  def edit
  end

  # POST /mods
  # POST /mods.json
  def create
    @mod = Mod.new(mod_params)

    respond_to do |format|
      if @mod.save
        format.html { redirect_to @mod, notice: 'Mod was successfully created.' }
        format.json { render :show, status: :created, location: @mod }
      else
        format.html { render :new }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mods/1
  # PATCH/PUT /mods/1.json
  def update
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to @mod, notice: 'Mod was successfully updated.' }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1
  # DELETE /mods/1.json
  def destroy
    @mod.destroy
    respond_to do |format|
      format.html { redirect_to mods_url, notice: 'Mod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mod
      @mod = Mod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mod_params
      params.require(:mod).permit(:name, :flavor)
    end
end

AVR_System/app/helpers/mods_helper.rb
module ModsHelper
end

AVR_System/app/views/mods/_form.html.erb
<%= form_with(model: mod, local: true) do |form| %>
  <% if mod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mod.errors.count, "error") %> prohibited this mod from being saved:</h2>

      <ul>
      <% mod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :flavor %>
    <%= form.text_field :flavor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

AVR_System/app/views/mods/edit.html.erb
<h1>Editing Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Show', @mod %> |
<%= link_to 'Back', mods_path %>

AVR_System/app/views/mods/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center"> Mods</h1><hr>


  <!--<thead>
    <tr>
      <th>Name</th>
      <th>Flavor</th>
      <th colspan="3"></th>
    </tr>
  </thead>-->


<div class="group">
  <div class="cheese">
    <p>Cheese</p>
  </div><hr>

  <% @mods.each do |mod| %>

  <tbody>
  <table id="items">
    <% if mod.name == 'Cheese' %>
    <tr>
      <td><%= mod.flavor %></td>


        <td>
            <label class="switch">
            <input type="checkbox" onclick= <% check_box("tag", tag.id, {checked: true})%> >
            <span class="slider round"></span>
          </label>

       </td>
    </tr>


  <% end %>

  <% end %>


  </table>
  </tbody>
</div>

<div class="group">
  <div class="cheese">
    <p>Chile Sauce</p>
  </div><hr>

  <% @mods.each do |mod| %>

    <tbody>
    <table id="items">
      <% if mod.name == 'Chile Sauce' %>
        <tr>
          <td><%= mod.flavor %></td>


          <td>
            <label class="switch">
              <input type="checkbox">
              <span class="slider round"></span>
            </label>

          </td>
        </tr>


      <% end %>

  <% end %>


  </table>
  </tbody>
</div>

<div class="groupsingle">


  <% @mods.each do |mod| %>

    <tbody>
    <table id="items">
      <% if mod.name != 'Chile Sauce' && mod.name != 'Cheese' %>
        <tr>
          <td><%= mod.name %></td>


          <td>
            <label class="switch">
              <input type="checkbox">
              <span class="slider round"></span>
            </label>

          </td>
        </tr>


      <% end %>

  <% end %>


  </table>
  </tbody>
</div>





<%#= link_to 'New Mod', new_mod_path %>

AVR_System/app/views/mods/new.html.erb
<h1>New Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Back', mods_path %>

AVR_System/app/views/mods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mod.name %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @mod.flavor %>
</p>

<%= link_to 'Edit', edit_mod_path(@mod) %> |
<%= link_to 'Back', mods_path %>