AVR_System/config/routes.rb
Rails.application.routes.draw do
  resources :items_mods_joins
  resources :mods
  resources :menuitems
  resources :categories
  resources :tables
  resources :tables_items_joins
  get 'sessions/new'
  resources :waiters

  match "/signout" => "sessions#destroy", via: [:get,:post]
  match "/signin" => "sessions#new", via: [:get,:post]
  match "/login" => "sessions#create", via: [:get,:post]

  root to: 'waiters#index'
end

AVR_System/app/models/menuitem.rb
class Menuitem < ApplicationRecord
  belongs_to :category
  has_many :tables_items_joins
  has_many :tables, through: :tables_items_joins
end

AVR_System/app/controllers/menuitems_controller.rb
class MenuitemsController < ApplicationController
  before_action :set_menuitem, only: [:show, :edit, :update, :destroy]

  # GET /menuitems
  # GET /menuitems.json
  def index
    @menuitems = Menuitem.all.where(category_id: params[:category_id])

    respond_to do |format|
      format.html
    end
  end

  def menuitembuttons
    @menuitems = Menuitem.all
  end

  # GET /menuitems/1
  # GET /menuitems/1.json
  def show
  end

  # GET /menuitems/new
  def new
    @menuitem = Menuitem.new
  end

  # GET /menuitems/1/edit
  def edit
  end

  # POST /menuitems
  # POST /menuitems.json
  def create
    @menuitem = Menuitem.new(menuitem_params)

    respond_to do |format|
      if @menuitem.save
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully created.' }
        format.json { render :show, status: :created, location: @menuitem }
      else
        format.html { render :new }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menuitems/1
  # PATCH/PUT /menuitems/1.json
  def update
    respond_to do |format|
      if @menuitem.update(menuitem_params)
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @menuitem }
      else
        format.html { render :edit }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menuitems/1
  # DELETE /menuitems/1.json
  def destroy
    @menuitem.destroy
    respond_to do |format|
      format.html { redirect_to menuitems_url, notice: 'Menuitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_menuitem
      @menuitem = Menuitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menuitem_params
      params.require(:menuitem).permit(:name, :category_id)
    end
end

AVR_System/app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

AVR_System/app/views/menuitems/_form.html.erb
<%= form_with(model: menuitem, local: true) do |form| %>
  <% if menuitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menuitem.errors.count, "error") %> prohibited this menuitem from being saved:</h2>

      <ul>
      <% menuitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

AVR_System/app/views/menuitems/_menuitembuttons.html.erb
<% @cat_id = Menuitem.all.where(category_id: @category_id) %>

<div class="fooditems">
  <% @cat_id.each do |item| %>

    <div class="food_flex">
      <div class="food_image"><%= link_to image_tag("#{item.name}.png", class: "item_images"), tables_items_joins_path(table_id: @table.id, menuitem_id: item.id), method: :post %></div>
      <div class="food_text"><%= item.name %></div>
      <div class="food_price"><%= "$#{item.price}" %></div>
    </div>
  <% end %>
</div>

AVR_System/app/views/menuitems/edit.html.erb
<h1>Editing Menuitem</h1>

<%= render 'form', menuitem: @menuitem %>

<%= link_to 'Show', @menuitem %> |
<%= link_to 'Back', menuitems_path %>

AVR_System/app/views/menuitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menuitems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menuitems.each do |menuitem| %>
      <tr>
        <td><%= menuitem.name %></td>
        <td><%= menuitem.category %></td>
        <td><%= link_to 'Show', menuitem %></td>
        <td><%= link_to 'Edit', edit_menuitem_path(menuitem) %></td>
        <td><%= link_to 'Destroy', menuitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menuitem', new_menuitem_path %>

AVR_System/app/views/menuitems/new.html.erb
<h1>New Menuitem</h1>

<%= render 'form', menuitem: @menuitem %>

<%= link_to 'Back', menuitems_path %>

AVR_System/app/views/menuitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menuitem.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @menuitem.category %>
</p>

<%= link_to 'Edit', edit_menuitem_path(@menuitem) %> |
<%= link_to 'Back', menuitems_path %>