AVR_System/config/routes.rb
Rails.application.routes.draw do
  resources :items_mods_joins
  resources :mods
  resources :menuitems
  resources :categories
  resources :tables
  resources :tables_items_joins
  get 'sessions/new'
  resources :waiters

  match "/signout" => "sessions#destroy", via: [:get,:post]
  match "/signin" => "sessions#new", via: [:get,:post]
  match "/login" => "sessions#create", via: [:get,:post]

  root to: 'waiters#index'
end

AVR_System/app/models/items_mods_join.rb
class ItemsModsJoin < ApplicationRecord
  belongs_to :menuitems
  belongs_to :mods
end

AVR_System/app/controllers/items_mods_joins_controller.rb
class ItemsModsJoinsController < ApplicationController
  before_action :set_items_mods_join, only: [:show, :edit, :update, :destroy]

  # GET /items_mods_joins
  # GET /items_mods_joins.json
  def index
    @items_mods_joins = ItemsModsJoin.all
  end

  # GET /items_mods_joins/1
  # GET /items_mods_joins/1.json
  def show
  end

  # GET /items_mods_joins/new
  def new
    @items_mods_join = ItemsModsJoin.new
  end

  # GET /items_mods_joins/1/edit
  def edit
  end

  # POST /items_mods_joins
  # POST /items_mods_joins.json
  def create
    @items_mods_join = ItemsModsJoin.new(items_mods_join_params)

    respond_to do |format|
      if @items_mods_join.save
        format.html { redirect_to @items_mods_join, notice: 'Items mods join was successfully created.' }
        format.json { render :show, status: :created, location: @items_mods_join }
      else
        format.html { render :new }
        format.json { render json: @items_mods_join.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items_mods_joins/1
  # PATCH/PUT /items_mods_joins/1.json
  def update
    respond_to do |format|
      if @items_mods_join.update(items_mods_join_params)
        format.html { redirect_to @items_mods_join, notice: 'Items mods join was successfully updated.' }
        format.json { render :show, status: :ok, location: @items_mods_join }
      else
        format.html { render :edit }
        format.json { render json: @items_mods_join.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items_mods_joins/1
  # DELETE /items_mods_joins/1.json
  def destroy
    @items_mods_join.destroy
    respond_to do |format|
      format.html { redirect_to items_mods_joins_url, notice: 'Items mods join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_items_mods_join
      @items_mods_join = ItemsModsJoin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def items_mods_join_params
      params.require(:items_mods_join).permit(:menuitems_id, :mods_id)
    end
end

AVR_System/app/helpers/items_mods_joins_helper.rb
module ItemsModsJoinsHelper
end

AVR_System/app/views/items_mods_joins/_form.html.erb
<%= form_with(model: items_mods_join, local: true) do |form| %>
  <% if items_mods_join.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(items_mods_join.errors.count, "error") %> prohibited this items_mods_join from being saved:</h2>

      <ul>
      <% items_mods_join.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :menuitems_id %>
    <%= form.text_field :menuitems_id %>
  </div>

  <div class="field">
    <%= form.label :mods_id %>
    <%= form.text_field :mods_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

AVR_System/app/views/items_mods_joins/edit.html.erb
<h1>Editing Items Mods Join</h1>

<%= render 'form', items_mods_join: @items_mods_join %>

<%= link_to 'Show', @items_mods_join %> |
<%= link_to 'Back', items_mods_joins_path %>

AVR_System/app/views/items_mods_joins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items Mods Joins</h1>

<table>
  <thead>
    <tr>
      <th>Menuitems</th>
      <th>Mods</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items_mods_joins.each do |items_mods_join| %>
      <tr>
        <td><%= items_mods_join.menuitems %></td>
        <td><%= items_mods_join.mods %></td>
        <td><%= link_to 'Show', items_mods_join %></td>
        <td><%= link_to 'Edit', edit_items_mods_join_path(items_mods_join) %></td>
        <td><%= link_to 'Destroy', items_mods_join, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Items Mods Join', new_items_mods_join_path %>

AVR_System/app/views/items_mods_joins/new.html.erb
<h1>New Items Mods Join</h1>

<%= render 'form', items_mods_join: @items_mods_join %>

<%= link_to 'Back', items_mods_joins_path %>

AVR_System/app/views/items_mods_joins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menuitems:</strong>
  <%= @items_mods_join.menuitems %>
</p>

<p>
  <strong>Mods:</strong>
  <%= @items_mods_join.mods %>
</p>

<%= link_to 'Edit', edit_items_mods_join_path(@items_mods_join) %> |
<%= link_to 'Back', items_mods_joins_path %>